name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mcu:
          - stm32f301
          - stm32f302
          - stm32f303
          - stm32f373
          - stm32f3x4
          - stm32l4x1
          - stm32l4x2
          - stm32l4x3
          - stm32l4x5
          - stm32l4x6
          - stm32l552
          - stm32l562

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv7em-none-eabihf
          override: true
          profile: minimal
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --features=${{ matrix.mcu }},${{ matrix.features }} --lib --examples

  check-tests:
    name: Check Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - rcc
        mcu:
          - stm32f303xc
          - stm32f303xd
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv7em-none-eabihf
          override: true
          profile: minimal
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --features=rt,defmt,${{ matrix.mcu }} --test ${{ matrix.test }}

