name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mcu:
          - f301
          - f302
          - f303
          - f373
          - f3x4
          - l4x1
          - l4x2
          - l4x3
          - l4x5
          - l4x6
          - l552
          - l562
          - h743
          - h743v
          - h747cm4
          - h747cm7
          - h753
          - h753v
          - h7b3

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv7em-none-eabihf
          override: true
          profile: minimal
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --features=${{ matrix.mcu }},${{ matrix.features }} --lib --examples

